### ISSUE TITLE
Integration in Laravel 5 doesn’t work

### ISSUE THREAD

**Issue by rbugajewski** [mathiasgrimm/laravel-dot-env-gen#5]
After adding the service provider with:

```
'mathiasgrimm\laraveldotenvgen\ServiceProvider',
```

my Laravel app complains that it can’t find the corresponding class.

`php artisan env:gen` worked, but I had to comment out the service provider afterwards.

**Comment by mathiasgrimm** [comment]
Have you updated the composer.json and ran composer update?

**Comment by rbugajewski** [comment]
Yes, I’ve run `composer update`. I get an exception in `ProviderRepository::createProvider()` whenever I try to access the app through the browser:

    Symfony \ Component \ Debug \ Exception \  FatalErrorException (E_ERROR)
    Class 'mathiasgrimm\laraveldotenvgen\ServiceProvider' not found

**Comment by rbugajewski** [comment]
Yes, I’ve run `composer update`. I get an exception in `ProviderRepository::createProvider()` whenever I try to access the app through the browser:

```
Symfony \ Component \ Debug \ Exception \  FatalErrorException (E_ERROR)
Class 'mathiasgrimm\laraveldotenvgen\ServiceProvider' not found
```
